apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-brukernotifikasjon-feilrespons-v1
  namespace: min-side
  labels:
    team: min-side
  annotations:
    dcat.data.nav.no/title: "Public topic for Dittnav sine feilrespons-eventer"
    dcat.data.nav.no/description: "Produsenter får tilbakemelding etter veil ved sending av andre eventer"
    dcat.data.nav.no/keyword: "brukernotifikasjon"
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 4
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 168  # One week
  acl:
    - team: min-side
      application: dittnav-brukernotifikasjonbestiller
      access: write  # read, write, readwrite
